Fixes iOS 11 issue
s4cha/KeyboardLayoutGuide pull request #9
Opened 2017-12-08 10:34 UTC by s4cha

We have a set of signup screens that are pushed one after another.

Everything works fine if we call `becomeFirstResponder()` in `viewDidAppear`
the `keyboardWillChangeFrame` is called and everything works as expected.

The thing is calling `becomeFirstResponder` in `viewDidAppear` animates the keyboard.

If we want to have the keyboard stay in position (already shown) in the screens,
we can call `becomeFirstResponder` in viewDidLoad.

In iOS 11, the issue is that the keyboard notifications are not called if the keyboard is already on screen
so we end up with the button under the keyboard.
The underlying reason is that `keyboardWillChangeFrame` is not called on IOS11 if the keyboard stays shown between controllers, which seems quite logical actually.

The fix stores the previous keyboard height and sets in back up when setting up a new controller, only if the device is running iOS 11 :)

2017-12-11 12:34 UTC, maxkonovalov requested changes

2017-12-11 12:34 UTC, maxkonovalov commented on KeyboardLayoutGuide/KeyboardLayoutGuide/Keyboard+LayoutGuide.swift
> +                heightAnchor.constraint(equalToConstant: Keyboard.shared.currentHeight),
Better to conditionally calculate only the constant in if-else here, leaving a single `NSLayoutConstraint.activate([...])` part (no repeating code)

2017-12-11 12:37 UTC, maxkonovalov commented
@s4cha do you think the iOS 11 check is necessary at all for the height caching? Having the height ready doesn't seem to be a bad idea, just need to make sure it works correctly on all versions.

2017-12-12 09:45 UTC, s4cha commented
@maxkonovalov I agree, I narrowed it down to iOS 11 to be specific but as you point out, it adds unnecessary complexity.

2017-12-12 11:25 UTC, maxkonovalov approved these changes

2017-12-12 11:26 UTC, maxkonovalov commented
👍

2017-12-12 13:57 UTC, merged